import { redirect } from "next/navigation";
import { getSession, isSchoolStaff } from "@/lib/auth/session";
import { listAttendance } from "@/lib/data/records";
import { listStudents } from "@/lib/data/students";
import { listClasses, listSections } from "@/lib/data/academics";
import { PrintButton } from "@/components/timetable/print-button";
import {
  buildAbsenteeReport,
  buildClassAttendanceReport,
  buildDailyAttendanceReport,
  buildLowAttendanceReport,
  buildMonthlyAttendanceReport,
  buildStudentAttendanceHistory,
  type AttendanceReportDataset,
} from "@/lib/reports/attendance-reports";

const TITLES: Record<string, string> = {
  daily: "Daily Attendance", monthly: "Monthly Attendance", student: "Student Attendance History",
  class: "Class Attendance", low: "Low Attendance Report", absentee: "Absentee Report",
};

function Table({ headers, rows }: { headers: string[]; rows: (string | number)[][] }) {
  return (
    <table className="w-full border-collapse text-sm">
      <thead><tr>{headers.map((h) => <th key={h} className="border border-border px-2 py-1.5 text-left">{h}</th>)}</tr></thead>
      <tbody>{rows.map((r, i) => <tr key={i}>{r.map((c, j) => <td key={j} className="border border-border px-2 py-1.5">{c}</td>)}</tr>)}</tbody>
    </table>
  );
}

export default async function PrintAttendanceReportPage({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!isSchoolStaff(session.profile.role)) redirect("/dashboard");

  const params = await searchParams;
  const key = params.key ?? "daily";
  const [attendance, students, classes, sections] = await Promise.all([listAttendance(), listStudents(), listClasses(), listSections()]);
  const data: AttendanceReportDataset = { attendance, students, classes, sections };

  let body: React.ReactNode = null;
  if (key === "daily") {
    const rows = buildDailyAttendanceReport(data, params.date ?? new Date().toISOString().slice(0, 10));
    body = <Table headers={["Student", "Class", "Section", "Status"]} rows={rows.map((r) => [r.student, r.class, r.section, r.status])} />;
  } else if (key === "monthly") {
    const rows = buildMonthlyAttendanceReport(data, Number(params.month ?? new Date().getMonth() + 1), Number(params.year ?? new Date().getFullYear()));
    body = <Table headers={["Student", "Present", "Absent", "Late", "Leave", "%"]} rows={rows.map((r) => [r.student, r.present, r.absent, r.late, r.leave, r.percentage])} />;
  } else if (key === "student") {
    const rows = buildStudentAttendanceHistory(data, params.studentId ?? "");
    body = <Table headers={["Date", "Status", "Remarks"]} rows={rows.map((r) => [r.date, r.status, r.remarks])} />;
  } else if (key === "class") {
    const rows = buildClassAttendanceReport(data, params.date ?? new Date().toISOString().slice(0, 10));
    body = <Table headers={["Class", "Present", "Absent", "Late", "Leave", "Total"]} rows={rows.map((r) => [r.class, r.present, r.absent, r.late, r.leave, r.total])} />;
  } else if (key === "low") {
    const rows = buildLowAttendanceReport(data, Number(params.threshold ?? 75));
    body = <Table headers={["Student", "Class", "Days Recorded", "%"]} rows={rows.map((r) => [r.student, r.class, r.totalDays, r.percentage])} />;
  } else {
    const rows = buildAbsenteeReport(data, params.date ?? new Date().toISOString().slice(0, 10));
    body = <Table headers={["Student", "Class", "Contact"]} rows={rows.map((r) => [r.student, r.class, r.contact])} />;
  }

  return (
    <div className="mx-auto max-w-4xl p-6 print:p-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <p className="text-sm text-muted">Print preview</p>
        <PrintButton />
      </div>
      <header className="mb-6 border-b-2 border-border pb-4 text-center">
        <h1 className="text-lg font-bold uppercase tracking-wide">{session.school.name}</h1>
        <p className="mt-2 text-base font-semibold">{TITLES[key] ?? "Attendance Report"}</p>
      </header>
      {body}
      <p className="mt-10 text-center text-xs text-muted">Generated by {session.profile.full_name} on {new Date().toLocaleString()} — {session.school.name}</p>
    </div>
  );
}
