import { redirect } from "next/navigation";
import { getSession, isFinanceStaff } from "@/lib/auth/session";
import { listFees, listPayments, listRefunds, listDiscounts, listScholarships, listFeeDiscounts } from "@/lib/data/finance";
import { listStudents } from "@/lib/data/students";
import { listClasses } from "@/lib/data/academics";
import { Card, CardHeader, EmptyState } from "@/components/ui/card";
import { ExportButton } from "@/components/finance/reports-center";

export default async function FinanceReportsPage() {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!isFinanceStaff(session.profile.role)) redirect("/fees");

  const [fees, payments, refunds, discounts, scholarships, feeDiscounts, students, classes] = await Promise.all([
    listFees(),
    listPayments(),
    listRefunds(),
    listDiscounts(),
    listScholarships(),
    listFeeDiscounts(),
    listStudents(),
    listClasses(),
  ]);

  const generatedLine = `${session.school.name} · Generated by ${session.profile.full_name} on ${new Date().toLocaleString()}`;

  // 1. Collection report
  const totalCollected = payments.reduce((s, p) => s + p.amount_paid, 0);

  // 2. Outstanding by class
  const outstandingByClass = classes.map((c) => ({
    name: c.name,
    balance: fees.filter((f) => students.find((s) => s.id === f.student_id)?.class_id === c.id).reduce((s, f) => s + f.balance, 0),
  }));

  // 3. Payment method breakdown
  const methodTotals = new Map<string, number>();
  for (const p of payments) methodTotals.set(p.payment_method, (methodTotals.get(p.payment_method) ?? 0) + p.amount_paid);

  // 4. Discount & scholarship summary
  const discountTotal = feeDiscounts.filter((fd) => fd.discount_id).reduce((s, fd) => s + fd.applied_amount, 0);
  const scholarshipTotal = feeDiscounts.filter((fd) => fd.scholarship_id).reduce((s, fd) => s + fd.applied_amount, 0);

  // 5. Defaulters (overdue balance)
  const defaulters = fees
    .filter((f) => f.status === "overdue")
    .map((f) => ({ student: students.find((s) => s.id === f.student_id), fee: f }))
    .sort((a, b) => b.fee.balance - a.fee.balance);

  // 6. Refunds report
  const totalRefunded = refunds.reduce((s, r) => s + r.amount, 0);

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-xl font-semibold">Finance Reports</h1>
        <p className="text-sm text-muted">{generatedLine}</p>
      </div>

      <Card>
        <CardHeader
          title="Fee Collection Report"
          action={<ExportButton filename="collection-report.csv" headers={["Receipt #", "Student", "Date", "Method", "Amount"]} rows={payments.map((p) => [p.receipt_number, students.find((s) => s.id === p.student_id)?.full_name ?? "", p.payment_date, p.payment_method, p.amount_paid])} />}
        />
        <div className="p-4 text-sm">
          <p>Total collected: <span className="font-semibold text-success">PKR {totalCollected.toLocaleString()}</span> across {payments.length} payment(s).</p>
        </div>
      </Card>

      <Card>
        <CardHeader
          title="Outstanding Fees by Class"
          action={<ExportButton filename="outstanding-by-class.csv" headers={["Class", "Outstanding Balance"]} rows={outstandingByClass.map((c) => [c.name, c.balance])} />}
        />
        <ul className="divide-y divide-border">
          {outstandingByClass.map((c) => (
            <li key={c.name} className="flex items-center justify-between px-5 py-2.5 text-sm">
              <span>{c.name}</span>
              <span className={c.balance > 0 ? "font-semibold text-danger" : "text-muted"}>PKR {c.balance.toLocaleString()}</span>
            </li>
          ))}
        </ul>
      </Card>

      <Card>
        <CardHeader
          title="Payment Method Breakdown"
          action={<ExportButton filename="payment-methods.csv" headers={["Method", "Total"]} rows={Array.from(methodTotals.entries())} />}
        />
        {methodTotals.size === 0 ? (
          <EmptyState label="No payments yet." />
        ) : (
          <ul className="divide-y divide-border">
            {Array.from(methodTotals.entries()).map(([method, total]) => (
              <li key={method} className="flex items-center justify-between px-5 py-2.5 text-sm capitalize">
                <span>{method.replace("_", " ")}</span>
                <span className="font-semibold">PKR {total.toLocaleString()}</span>
              </li>
            ))}
          </ul>
        )}
      </Card>

      <Card>
        <CardHeader title="Discounts & Scholarships Summary" />
        <div className="grid grid-cols-2 gap-3 p-4 text-sm">
          <div className="rounded-lg bg-accent/5 p-3">
            <p className="text-xs text-muted">Discounts Applied ({discounts.length} defined)</p>
            <p className="text-lg font-semibold text-accent">PKR {discountTotal.toLocaleString()}</p>
          </div>
          <div className="rounded-lg bg-primary/5 p-3">
            <p className="text-xs text-muted">Scholarships Applied ({scholarships.filter((s) => s.status === "approved").length} approved)</p>
            <p className="text-lg font-semibold text-primary">PKR {scholarshipTotal.toLocaleString()}</p>
          </div>
        </div>
      </Card>

      <Card>
        <CardHeader
          title="Defaulters List (Overdue)"
          action={<ExportButton filename="defaulters.csv" headers={["Student", "Admission #", "Fee", "Due Date", "Balance"]} rows={defaulters.map((d) => [d.student?.full_name ?? "", d.student?.admission_number ?? "", d.fee.title, d.fee.due_date, d.fee.balance])} />}
        />
        {defaulters.length === 0 ? (
          <EmptyState label="No overdue charges — great collection rate!" />
        ) : (
          <ul className="divide-y divide-border">
            {defaulters.slice(0, 20).map((d) => (
              <li key={d.fee.id} className="flex items-center justify-between px-5 py-2.5 text-sm">
                <span>{d.student?.full_name} — {d.fee.title}</span>
                <span className="font-semibold text-danger">PKR {d.fee.balance.toLocaleString()}</span>
              </li>
            ))}
          </ul>
        )}
      </Card>

      <Card>
        <CardHeader
          title="Refunds Report"
          action={<ExportButton filename="refunds-report.csv" headers={["Student", "Amount", "Reason", "Date"]} rows={refunds.map((r) => [students.find((s) => s.id === r.student_id)?.full_name ?? "", r.amount, r.reason, r.created_at ?? ""])} />}
        />
        <div className="p-4 text-sm">
          <p>Total refunded: <span className="font-semibold text-danger">PKR {totalRefunded.toLocaleString()}</span> across {refunds.length} refund(s).</p>
        </div>
      </Card>
    </div>
  );
}
