import { redirect } from "next/navigation";
import { getSession, isFinanceStaff } from "@/lib/auth/session";
import { listFees, listPayments, listRefunds, listDiscounts, listScholarships, listFeeDiscounts, listFeeStructures, listFeePeriods } from "@/lib/data/finance";
import { listStudents } from "@/lib/data/students";
import { listClasses, listSections } from "@/lib/data/academics";
import { listProfiles } from "@/lib/data/profiles";
import { FinanceReportsCenter } from "@/components/finance/finance-reports-center";
import type { FinanceDataset } from "@/lib/reports/finance-reports";

export default async function FinanceReportsPage() {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!isFinanceStaff(session.profile.role)) redirect("/fees");

  const [fees, payments, refunds, discounts, scholarships, feeDiscounts, feeStructures, feePeriods, students, classes, sections, profiles] =
    await Promise.all([
      listFees(),
      listPayments(),
      listRefunds(),
      listDiscounts(),
      listScholarships(),
      listFeeDiscounts(),
      listFeeStructures(),
      listFeePeriods(),
      listStudents(),
      listClasses(),
      listSections(),
      listProfiles(),
    ]);

  const data: FinanceDataset = {
    fees,
    payments,
    refunds,
    discounts,
    scholarships,
    feeDiscounts,
    feeStructures,
    feePeriods,
    students,
    classes,
    sections,
    profiles,
  };

  const generatedLine = `${session.school.name} · Generated by ${session.profile.full_name} on ${new Date().toLocaleString()}`;

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-xl font-semibold">Finance Reports</h1>
        <p className="text-sm text-muted">All 11 finance report types, computed from real records, each exportable as CSV, Excel, or Print/PDF.</p>
      </div>
      <FinanceReportsCenter data={data} generatedLine={generatedLine} />
    </div>
  );
}
