import { redirect } from "next/navigation";
import { getSession, isSchoolStaff } from "@/lib/auth/session";
import { listVehicles, listDrivers, listRoutes, listRouteStops, listRouteStudents } from "@/lib/data/transport";
import { listStudents } from "@/lib/data/students";
import { listFees } from "@/lib/data/finance";
import { PrintButton } from "@/components/timetable/print-button";
import {
  buildCapacityReport,
  buildDriverReport,
  buildRouteReport,
  buildStudentTransportReport,
  buildTransportFeeReport,
  buildVehicleReport,
  type TransportDataset,
} from "@/lib/reports/transport-reports";

const TITLES: Record<string, string> = {
  vehicle: "Vehicle Report",
  driver: "Driver Report",
  route: "Route Report",
  student: "Student Transport Report",
  capacity: "Capacity Report",
  fee: "Transport Fee Report",
};

function Table({ headers, rows }: { headers: string[]; rows: (string | number)[][] }) {
  return (
    <table className="w-full border-collapse text-sm">
      <thead>
        <tr>{headers.map((h) => <th key={h} className="border border-border px-2 py-1.5 text-left">{h}</th>)}</tr>
      </thead>
      <tbody>
        {rows.map((r, i) => (
          <tr key={i}>{r.map((c, j) => <td key={j} className="border border-border px-2 py-1.5">{c}</td>)}</tr>
        ))}
      </tbody>
    </table>
  );
}

export default async function PrintTransportReportPage({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!isSchoolStaff(session.profile.role)) redirect("/transport");

  const { key = "vehicle" } = await searchParams;
  const [vehicles, drivers, routes, stops, assignments, students, fees] = await Promise.all([
    listVehicles(), listDrivers(), listRoutes(), listRouteStops(), listRouteStudents(), listStudents(), listFees(),
  ]);
  const data: TransportDataset = { vehicles, drivers, routes, stops, assignments, students, fees };

  let body: React.ReactNode = null;
  if (key === "vehicle") {
    const rows = buildVehicleReport(data);
    body = <Table headers={["Vehicle", "Type", "Capacity", "Assigned", "Driver", "Status"]} rows={rows.map((r) => [r.vehicleNumber, r.type, r.capacity, r.assigned, r.driver, r.status])} />;
  } else if (key === "driver") {
    const rows = buildDriverReport(data);
    body = <Table headers={["Driver", "Employee ID", "Mobile", "License #", "License Expiry", "Vehicle", "Status"]} rows={rows.map((r) => [r.name, r.employeeId, r.mobile, r.licenseNumber, r.licenseExpiry, r.vehicle, r.status])} />;
  } else if (key === "route") {
    const rows = buildRouteReport(data);
    body = <Table headers={["Route", "Code", "Starting Point", "Destination", "Vehicle", "Stops", "Assigned", "Fare", "Status"]} rows={rows.map((r) => [r.name, r.code, r.startingPoint, r.destination, r.vehicle, r.stops, r.assignedStudents, `PKR ${r.fare}`, r.status])} />;
  } else if (key === "student") {
    const rows = buildStudentTransportReport(data);
    body = <Table headers={["Student", "Admission #", "Route", "Stop", "Since"]} rows={rows.map((r) => [r.student, r.admissionNumber, r.route, r.stop, r.startDate])} />;
  } else if (key === "capacity") {
    const rows = buildCapacityReport(data);
    body = <Table headers={["Route", "Vehicle", "Capacity", "Assigned", "Available", "Utilization %"]} rows={rows.map((r) => [r.route, r.vehicle, r.capacity, r.assigned, r.availableSeats, r.utilization])} />;
  } else {
    const rows = buildTransportFeeReport(data);
    body = <Table headers={["Student", "Fee", "Amount", "Discount", "Due Date", "Status"]} rows={rows.map((r) => [r.student, r.title, `PKR ${r.amount}`, `PKR ${r.discount}`, r.dueDate, r.status])} />;
  }

  return (
    <div className="mx-auto max-w-4xl p-6 print:p-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <p className="text-sm text-muted">Print preview</p>
        <PrintButton />
      </div>
      <header className="mb-6 border-b-2 border-border pb-4 text-center">
        <h1 className="text-lg font-bold uppercase tracking-wide">{session.school.name}</h1>
        <p className="mt-2 text-base font-semibold">{TITLES[key] ?? "Transport Report"}</p>
      </header>
      {body}
      <p className="mt-10 text-center text-xs text-muted">
        Generated by {session.profile.full_name} on {new Date().toLocaleString()} — {session.school.name}
      </p>
    </div>
  );
}
