import { notFound, redirect } from "next/navigation";
import { getSession, isSchoolStaff } from "@/lib/auth/session";
import { listClasses, listSections } from "@/lib/data/academics";
import { listStudents } from "@/lib/data/students";
import { listAttendance, listHomework } from "@/lib/data/records";
import { listHomeworkAssignments } from "@/lib/data/homework-submissions";
import { listExams } from "@/lib/data/exams";
import { listResults } from "@/lib/data/results";
import { listFees } from "@/lib/data/finance";
import { listBookIssues } from "@/lib/data/library";
import { listRouteStudents } from "@/lib/data/transport";
import { buildClass360, type Class360Context } from "@/lib/reports/class-360";
import { recordAuditLog } from "@/lib/audit/log";
import { PrintButton } from "@/components/timetable/print-button";

const money = (n: number) => `PKR ${Math.round(n).toLocaleString()}`;

export default async function PrintClass360Page({ searchParams }: { searchParams: Promise<{ classId?: string; sectionId?: string }> }) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!isSchoolStaff(session.profile.role)) redirect("/dashboard");

  const { classId, sectionId } = await searchParams;
  if (!classId) notFound();

  const [classes, sections, students, attendance, homework, homeworkAssignments, exams, results, fees, bookIssues, transportAssignments] =
    await Promise.all([
      listClasses(), listSections(), listStudents(), listAttendance(), listHomework(), listHomeworkAssignments(),
      listExams(), listResults(), listFees(), listBookIssues(), listRouteStudents(),
    ]);

  const ctx: Class360Context = { classes, sections, students, attendance, exams, results, homework, homeworkAssignments, fees, bookIssues, transportAssignments };
  const report = buildClass360(classId, sectionId ?? null, ctx);

  await recordAuditLog({ schoolId: session.school.id, profileId: session.profile.id, action: "report.class_360_downloaded", targetTable: "classes", targetId: classId });

  return (
    <div className="mx-auto max-w-3xl p-6 print:p-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <p className="text-sm text-muted">Print preview</p>
        <PrintButton />
      </div>
      <header className="mb-6 border-b-2 border-border pb-4 text-center">
        <h1 className="text-lg font-bold uppercase tracking-wide">{session.school.name}</h1>
        <p className="mt-2 text-base font-semibold">CLASS 360 REPORT</p>
      </header>

      <p className="mb-4 text-sm"><strong>Class:</strong> {report.className}{report.sectionName ? ` - ${report.sectionName}` : ""} &nbsp; <strong>Students:</strong> {report.studentCount}</p>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Attendance</h2>
        <p className="mt-2 text-sm">Present: {report.attendance.present} · Absent: {report.attendance.absent} · Late: {report.attendance.late} · Leave: {report.attendance.leave} · Percentage: {report.attendance.percentage}%</p>
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Academic Performance</h2>
        <p className="mt-2 text-sm">Average: {report.academic.averagePercentage}% · Pass Rate: {report.academic.passRate}% · Passed: {report.academic.passCount} · Failed: {report.academic.failCount}</p>
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Fees Summary</h2>
        <p className="mt-2 text-sm">Expected: {money(report.fees.expected)} · Collected: {money(report.fees.collected)} · Outstanding: {money(report.fees.outstanding)}</p>
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Homework Completion</h2>
        <p className="mt-2 text-sm">Assigned: {report.homework.assignedCount} · Completion Rate: {report.homework.completionRate}%</p>
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Library Summary</h2>
        <p className="mt-2 text-sm">Currently Issued: {report.library.currentlyIssued} · Overdue: {report.library.overdue}</p>
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Transport Summary</h2>
        <p className="mt-2 text-sm">Assigned to Transport: {report.transport.assignedCount}</p>
      </section>

      <p className="mt-10 text-center text-xs text-muted">Generated by {session.profile.full_name} on {new Date().toLocaleString()} — {session.school.name}</p>
    </div>
  );
}
