import { redirect } from "next/navigation";
import { getSession, isSchoolStaff } from "@/lib/auth/session";
import { listStudents } from "@/lib/data/students";
import { listClasses, listSections } from "@/lib/data/academics";
import { listAcademicSessions } from "@/lib/data/sessions";
import { PrintButton } from "@/components/timetable/print-button";
import {
  buildAdmissionReport,
  buildClassWiseStudentReport,
  buildDemographicReport,
  buildEnrollmentReport,
  buildPromotionReport,
  buildSectionWiseStudentReport,
  buildStudentDirectory,
  buildWithdrawalReport,
  type StudentReportDataset,
} from "@/lib/reports/student-reports";

const TITLES: Record<string, string> = {
  directory: "Student Directory", enrollment: "Enrollment Report", class_wise: "Class-wise Student Report",
  section_wise: "Section-wise Student Report", admission: "Student Admission Report", promotion: "Student Promotion Report",
  withdrawal: "Student Withdrawal/Leaving Report", demographic: "Student Demographic Report",
};

function Table({ headers, rows }: { headers: string[]; rows: (string | number)[][] }) {
  return (
    <table className="w-full border-collapse text-sm">
      <thead><tr>{headers.map((h) => <th key={h} className="border border-border px-2 py-1.5 text-left">{h}</th>)}</tr></thead>
      <tbody>{rows.map((r, i) => <tr key={i}>{r.map((c, j) => <td key={j} className="border border-border px-2 py-1.5">{c}</td>)}</tr>)}</tbody>
    </table>
  );
}

export default async function PrintStudentReportPage({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!isSchoolStaff(session.profile.role)) redirect("/dashboard");

  const { key = "directory" } = await searchParams;
  const [students, classes, sections, sessions] = await Promise.all([listStudents(), listClasses(), listSections(), listAcademicSessions()]);
  const data: StudentReportDataset = { students, classes, sections, sessions };

  let body: React.ReactNode = null;
  if (key === "directory") {
    const rows = buildStudentDirectory(data);
    body = <Table headers={["Admission #", "Name", "Father's Name", "Class", "Section", "Roll #", "Contact", "Status"]} rows={rows.map((r) => [r.admissionNumber, r.name, r.fatherName, r.class, r.section, r.rollNumber, r.contact, r.status])} />;
  } else if (key === "enrollment") {
    const rows = buildEnrollmentReport(data);
    body = <Table headers={["Month", "New Admissions"]} rows={rows.map((r) => [r.month, r.newAdmissions])} />;
  } else if (key === "class_wise") {
    const rows = buildClassWiseStudentReport(data);
    body = <Table headers={["Class", "Students"]} rows={rows.map((r) => [r.class, r.studentCount])} />;
  } else if (key === "section_wise") {
    const rows = buildSectionWiseStudentReport(data);
    body = <Table headers={["Class", "Section", "Students", "Capacity"]} rows={rows.map((r) => [r.class, r.section, r.studentCount, r.capacity])} />;
  } else if (key === "admission") {
    const rows = buildAdmissionReport(data);
    body = <Table headers={["Admission #", "Name", "Admission Date", "Class", "Section"]} rows={rows.map((r) => [r.admissionNumber, r.name, r.admissionDate, r.class, r.section])} />;
  } else if (key === "promotion") {
    const rows = buildPromotionReport(data);
    body = <Table headers={["Academic Session", "Students"]} rows={rows.map((r) => [r.session, r.studentCount])} />;
  } else if (key === "withdrawal") {
    const rows = buildWithdrawalReport(data);
    body = <Table headers={["Admission #", "Name", "Class", "Section", "Status"]} rows={rows.map((r) => [r.admissionNumber, r.name, r.class, r.section, r.status])} />;
  } else {
    const rows = buildDemographicReport(data).byGender;
    body = <Table headers={["Gender", "Count"]} rows={rows.map((r) => [r.gender, r.count])} />;
  }

  return (
    <div className="mx-auto max-w-4xl p-6 print:p-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <p className="text-sm text-muted">Print preview</p>
        <PrintButton />
      </div>
      <header className="mb-6 border-b-2 border-border pb-4 text-center">
        <h1 className="text-lg font-bold uppercase tracking-wide">{session.school.name}</h1>
        <p className="mt-2 text-base font-semibold">{TITLES[key] ?? "Student Report"}</p>
      </header>
      {body}
      <p className="mt-10 text-center text-xs text-muted">Generated by {session.profile.full_name} on {new Date().toLocaleString()} — {session.school.name}</p>
    </div>
  );
}
