import { redirect } from "next/navigation";
import { getSession, isSchoolStaff } from "@/lib/auth/session";
import { listBooks, listBookIssues, getLibrarySettings } from "@/lib/data/library";
import { listStudents } from "@/lib/data/students";
import { listTeachers } from "@/lib/data/teachers";
import { PrintButton } from "@/components/timetable/print-button";
import {
  buildBooksInventoryReport,
  buildFineReport,
  buildIssuedBooksReport,
  buildMemberBorrowingReport,
  buildOverdueBooksReport,
  buildReturnedBooksReport,
  type LibraryDataset,
} from "@/lib/reports/library-reports";

const TITLES: Record<string, string> = {
  inventory: "Books Inventory Report",
  issued: "Issued Books Report",
  returned: "Returned Books Report",
  overdue: "Overdue Books Report",
  fines: "Fine Report",
  borrowing: "Member Borrowing Report",
};

function Table({ headers, rows }: { headers: string[]; rows: (string | number)[][] }) {
  return (
    <table className="w-full border-collapse text-sm">
      <thead>
        <tr>{headers.map((h) => <th key={h} className="border border-border px-2 py-1.5 text-left">{h}</th>)}</tr>
      </thead>
      <tbody>
        {rows.map((r, i) => (
          <tr key={i}>{r.map((c, j) => <td key={j} className="border border-border px-2 py-1.5">{c}</td>)}</tr>
        ))}
      </tbody>
    </table>
  );
}

export default async function PrintLibraryReportPage({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!isSchoolStaff(session.profile.role)) redirect("/library");

  const { key = "inventory" } = await searchParams;

  const [books, issues, students, teachers, settings] = await Promise.all([
    listBooks(),
    listBookIssues(),
    listStudents(),
    listTeachers(),
    getLibrarySettings(session.school.id),
  ]);
  const data: LibraryDataset = { books, issues, students, teachers, settings };

  let body: React.ReactNode = null;
  if (key === "inventory") {
    const rows = buildBooksInventoryReport(data);
    body = <Table headers={["Title", "Accession #", "Category", "Total", "Available", "Issued", "Status"]} rows={rows.map((r) => [r.title, r.accessionNumber, r.category, r.totalCopies, r.availableCopies, r.issuedCopies, r.status])} />;
  } else if (key === "issued") {
    const rows = buildIssuedBooksReport(data);
    body = <Table headers={["Book", "Borrower", "Issue Date", "Due Date", "Days Overdue"]} rows={rows.map((r) => [r.book, r.borrower, r.issueDate, r.dueDate, r.daysOverdue])} />;
  } else if (key === "returned") {
    const rows = buildReturnedBooksReport(data);
    body = <Table headers={["Book", "Borrower", "Issue Date", "Return Date", "Fine", "Condition"]} rows={rows.map((r) => [r.book, r.borrower, r.issueDate, r.returnDate, `PKR ${r.fine}`, r.condition])} />;
  } else if (key === "overdue") {
    const rows = buildOverdueBooksReport(data);
    body = <Table headers={["Book", "Borrower", "Due Date", "Days Overdue", "Fine"]} rows={rows.map((r) => [r.book, r.borrower, r.dueDate, r.daysOverdue, `PKR ${r.fine}`])} />;
  } else if (key === "fines") {
    const rows = buildFineReport(data);
    body = <Table headers={["Book", "Borrower", "Status", "Fine"]} rows={rows.map((r) => [r.book, r.borrower, r.status, `PKR ${r.fine}`])} />;
  } else {
    const rows = buildMemberBorrowingReport(data);
    body = <Table headers={["Member", "Total Issued", "Currently Issued", "Total Fines"]} rows={rows.map((r) => [r.name, r.totalIssued, r.currentlyIssued, `PKR ${r.totalFines}`])} />;
  }

  return (
    <div className="mx-auto max-w-4xl p-6 print:p-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <p className="text-sm text-muted">Print preview</p>
        <PrintButton />
      </div>
      <header className="mb-6 border-b-2 border-border pb-4 text-center">
        <h1 className="text-lg font-bold uppercase tracking-wide">{session.school.name}</h1>
        <p className="mt-2 text-base font-semibold">{TITLES[key] ?? "Library Report"}</p>
      </header>
      {body}
      <p className="mt-10 text-center text-xs text-muted">
        Generated by {session.profile.full_name} on {new Date().toLocaleString()} — {session.school.name}
      </p>
    </div>
  );
}
