import { notFound, redirect } from "next/navigation";
import { getSession, isFinanceStaff } from "@/lib/auth/session";
import { getStudentIdForProfile, getChildStudentIdsForProfile } from "@/lib/data/people";
import { listPayments, listPaymentAllocations, listFees } from "@/lib/data/finance";
import { getStudent } from "@/lib/data/students";
import { PrintButton } from "@/components/timetable/print-button";

export default async function PrintReceiptPage({ params }: { params: Promise<{ paymentId: string }> }) {
  const session = await getSession();
  if (!session) redirect("/login");

  const { paymentId } = await params;
  const payments = await listPayments();
  const payment = payments.find((p) => p.id === paymentId);
  if (!payment) notFound();

  if (!isFinanceStaff(session.profile.role)) {
    if (session.profile.role === "student") {
      const ownId = await getStudentIdForProfile(session.profile.id);
      if (ownId !== payment.student_id) redirect("/fees");
    } else if (session.profile.role === "parent") {
      const childIds = await getChildStudentIdsForProfile(session.profile.id);
      if (!childIds.includes(payment.student_id)) redirect("/fees");
    } else {
      redirect("/fees");
    }
  }

  const [student, allocations, fees] = await Promise.all([
    getStudent(payment.student_id),
    listPaymentAllocations(payment.id),
    listFees(),
  ]);

  return (
    <div className="mx-auto max-w-xl p-6 print:p-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <p className="text-sm text-muted">Print preview</p>
        <PrintButton />
      </div>

      <header className="mb-6 border-b-2 border-border pb-4 text-center">
        <h1 className="text-lg font-bold uppercase tracking-wide">{session.school.name}</h1>
        {session.school.address && <p className="text-sm text-muted">{session.school.address}</p>}
        <p className="mt-2 text-base font-semibold">Fee Payment Receipt</p>
      </header>

      <div className="mb-4 flex items-center justify-between text-sm">
        <div>
          <p className="font-medium">Receipt No.</p>
          <p className="text-base font-bold text-primary">{payment.receipt_number}</p>
        </div>
        <div className="text-right">
          <p className="font-medium">Date</p>
          <p>{new Date(payment.payment_date).toLocaleDateString()}</p>
        </div>
      </div>

      <div className="mb-4 rounded-lg border border-border p-3 text-sm">
        <p><span className="font-medium">Student:</span> {student?.full_name ?? "—"}</p>
        <p><span className="font-medium">Admission #:</span> {student?.admission_number ?? "—"}</p>
      </div>

      <table className="w-full border-collapse text-sm">
        <thead>
          <tr>
            <th className="border border-border px-2 py-2 text-left">Fee Charge</th>
            <th className="border border-border px-2 py-2 text-right">Amount Received</th>
          </tr>
        </thead>
        <tbody>
          {allocations.map((a) => (
            <tr key={a.id}>
              <td className="border border-border px-2 py-2">{fees.find((f) => f.id === a.fee_id)?.title ?? "Fee charge"}</td>
              <td className="border border-border px-2 py-2 text-right">PKR {a.amount.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr>
            <td className="border border-border px-2 py-2 text-right font-semibold">Total Paid</td>
            <td className="border border-border px-2 py-2 text-right font-semibold">PKR {payment.amount_paid.toLocaleString()}</td>
          </tr>
        </tfoot>
      </table>

      <div className="mt-4 grid grid-cols-2 gap-3 text-sm">
        <p><span className="font-medium">Payment Method:</span> <span className="capitalize">{payment.payment_method.replace("_", " ")}</span></p>
        {payment.notes && <p className="col-span-2"><span className="font-medium">Notes:</span> {payment.notes}</p>}
      </div>

      <p className="mt-10 text-center text-xs text-muted">
        Generated by {session.profile.full_name} on {new Date().toLocaleString()} — {session.school.name}
      </p>
    </div>
  );
}
