import { notFound, redirect } from "next/navigation";
import { getSession, isSchoolStaff } from "@/lib/auth/session";
import { getStudentIdForProfile, getChildStudentIdsForProfile } from "@/lib/data/people";
import { loadStudent360 } from "@/lib/reports/load-student-360";
import { recordAuditLog } from "@/lib/audit/log";
import { PrintButton } from "@/components/timetable/print-button";

const money = (n: number) => `PKR ${Math.round(n).toLocaleString()}`;

export default async function PrintStudent360Page({ searchParams }: { searchParams: Promise<{ studentId?: string }> }) {
  const session = await getSession();
  if (!session) redirect("/login");

  const { studentId } = await searchParams;
  if (!studentId) notFound();

  // Same authorization rule as the on-screen report: a parent/student can
  // never print another student's Student 360 by editing the URL.
  if (!isSchoolStaff(session.profile.role)) {
    const authorizedIds =
      session.profile.role === "student"
        ? [await getStudentIdForProfile(session.profile.id)].filter((id): id is string => !!id)
        : await getChildStudentIdsForProfile(session.profile.id);
    if (!authorizedIds.includes(studentId)) notFound();
  }

  const report = await loadStudent360(studentId, session.school.id, session.profile.role);
  if (!report) notFound();

  await recordAuditLog({ schoolId: session.school.id, profileId: session.profile.id, action: "report.student_360_downloaded", targetTable: "students", targetId: studentId });

  const { student, className, sectionName, academic, attendance, homework, finance, library, transport } = report;

  return (
    <div className="mx-auto max-w-3xl p-6 print:p-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <p className="text-sm text-muted">Print preview</p>
        <PrintButton />
      </div>

      <header className="mb-6 border-b-2 border-border pb-4 text-center">
        <h1 className="text-lg font-bold uppercase tracking-wide">{session.school.name}</h1>
        <p className="mt-2 text-base font-semibold">STUDENT 360 REPORT</p>
      </header>

      <p className="mb-4 text-sm"><strong>Student:</strong> {student.full_name} &nbsp; <strong>Class:</strong> {className} - {sectionName} &nbsp; <strong>Admission #:</strong> {student.admission_number}</p>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Academic</h2>
        {academic.latestResult ? (
          <p className="mt-2 text-sm">Latest Result: {academic.latestResult.exam.name} — {academic.latestResult.result.percentage}% ({academic.latestResult.result.grade ?? "—"}), {academic.latestResult.result.is_pass ? "Pass" : "Fail"}</p>
        ) : (
          <p className="mt-2 text-sm text-muted">No published results yet.</p>
        )}
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Attendance</h2>
        <p className="mt-2 text-sm">Present: {attendance.present} · Absent: {attendance.absent} · Late: {attendance.late} · Leave: {attendance.leave} · Percentage: {attendance.percentage}%</p>
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Finance</h2>
        <p className="mt-2 text-sm">Total Charges: {money(finance.totalCharged)} · Discount: {money(finance.totalDiscount)} · Paid: {money(finance.totalPaid)} · Outstanding: {money(finance.totalBalance)}</p>
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Homework</h2>
        <p className="mt-2 text-sm">Pending: {homework.pendingCount}</p>
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Library</h2>
        <p className="mt-2 text-sm">Books Issued: {library.issued} · Returned: {library.returned} · Outstanding: {library.currentlyIssued.length} · Fines: {money(library.totalFines)}</p>
      </section>

      <section className="mb-4">
        <h2 className="border-b border-border pb-1 text-sm font-semibold uppercase tracking-wide">Transport</h2>
        {transport ? (
          <p className="mt-2 text-sm">Route: {transport.route?.name ?? "—"} · Vehicle: {transport.vehicle?.vehicle_number ?? "—"} · Stop: {transport.stop?.stop_name ?? "—"}</p>
        ) : (
          <p className="mt-2 text-sm text-muted">Not assigned to school transport.</p>
        )}
      </section>

      <p className="mt-10 text-center text-xs text-muted">Generated by {session.profile.full_name} on {new Date().toLocaleString()} — {session.school.name}</p>
    </div>
  );
}
