import { redirect } from "next/navigation";
import { getSession, isSchoolAdmin } from "@/lib/auth/session";
import { listTeachers } from "@/lib/data/teachers";
import { listAssignments } from "@/lib/data/assignments";
import { listClasses, listSections } from "@/lib/data/academics";
import { listSubjects } from "@/lib/data/subjects";
import { PrintButton } from "@/components/timetable/print-button";
import { buildTeacherDirectory, buildTeacherWorkloadReport, type TeacherReportDataset } from "@/lib/reports/teacher-reports";

const TITLES: Record<string, string> = { directory: "Teacher Directory", workload: "Teacher Workload Report" };

function Table({ headers, rows }: { headers: string[]; rows: (string | number)[][] }) {
  return (
    <table className="w-full border-collapse text-sm">
      <thead><tr>{headers.map((h) => <th key={h} className="border border-border px-2 py-1.5 text-left">{h}</th>)}</tr></thead>
      <tbody>{rows.map((r, i) => <tr key={i}>{r.map((c, j) => <td key={j} className="border border-border px-2 py-1.5">{c}</td>)}</tr>)}</tbody>
    </table>
  );
}

export default async function PrintTeacherReportPage({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!isSchoolAdmin(session.profile.role)) redirect("/dashboard");

  const { key = "directory" } = await searchParams;
  const [teachers, assignments, classes, sections, subjects] = await Promise.all([
    listTeachers(), listAssignments(), listClasses(), listSections(), listSubjects(),
  ]);
  const data: TeacherReportDataset = { teachers, assignments, classes, sections, subjects };

  let body: React.ReactNode;
  if (key === "directory") {
    const rows = buildTeacherDirectory(data);
    body = <Table headers={["Employee ID", "Name", "Designation", "Qualification", "Mobile", "Status"]} rows={rows.map((r) => [r.employeeId, r.name, r.designation, r.qualification, r.mobile, r.status])} />;
  } else {
    const rows = buildTeacherWorkloadReport(data);
    body = <Table headers={["Teacher", "Classes", "Subjects", "Subject Names"]} rows={rows.map((r) => [r.name, r.classesAssigned, r.subjectsAssigned, r.subjects])} />;
  }

  return (
    <div className="mx-auto max-w-4xl p-6 print:p-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <p className="text-sm text-muted">Print preview</p>
        <PrintButton />
      </div>
      <header className="mb-6 border-b-2 border-border pb-4 text-center">
        <h1 className="text-lg font-bold uppercase tracking-wide">{session.school.name}</h1>
        <p className="mt-2 text-base font-semibold">{TITLES[key] ?? "Teacher Report"}</p>
      </header>
      {body}
      <p className="mt-10 text-center text-xs text-muted">Generated by {session.profile.full_name} on {new Date().toLocaleString()} — {session.school.name}</p>
    </div>
  );
}
