import { redirect } from "next/navigation";
import { getSession, isSchoolStaff } from "@/lib/auth/session";
import { listInventoryItems, listInventoryTransactions, listInventoryCategories } from "@/lib/data/inventory";
import { PrintButton } from "@/components/timetable/print-button";
import {
  buildAssetAssignmentReport,
  buildAssetValueReport,
  buildDamagedItemsReport,
  buildDisposedItemsReport,
  buildInventorySummary,
  buildLowStockReport,
  buildStockInReport,
  buildStockOutReport,
  buildUnderRepairReport,
  type InventoryDataset,
} from "@/lib/reports/inventory-reports";

const TITLES: Record<string, string> = {
  summary: "Inventory Summary",
  stock_in: "Stock In Report",
  stock_out: "Stock Out Report",
  assignment: "Asset Assignment Report",
  low_stock: "Low Stock Report",
  damaged: "Damaged Items Report",
  under_repair: "Items Under Repair",
  disposed: "Disposed Items Report",
  value: "Asset Value Report",
};

function Table({ headers, rows }: { headers: string[]; rows: (string | number)[][] }) {
  return (
    <table className="w-full border-collapse text-sm">
      <thead>
        <tr>{headers.map((h) => <th key={h} className="border border-border px-2 py-1.5 text-left">{h}</th>)}</tr>
      </thead>
      <tbody>
        {rows.map((r, i) => (
          <tr key={i}>{r.map((c, j) => <td key={j} className="border border-border px-2 py-1.5">{c}</td>)}</tr>
        ))}
      </tbody>
    </table>
  );
}

export default async function PrintInventoryReportPage({ searchParams }: { searchParams: Promise<Record<string, string>> }) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!isSchoolStaff(session.profile.role)) redirect("/dashboard");

  const { key = "summary" } = await searchParams;
  const [items, transactions, categories] = await Promise.all([listInventoryItems(), listInventoryTransactions(), listInventoryCategories()]);
  const data: InventoryDataset = { items, transactions, categories };

  let body: React.ReactNode = null;
  if (key === "summary") {
    const rows = buildInventorySummary(data);
    body = <Table headers={["Asset Code", "Name", "Category", "Quantity", "Available", "Unit Cost", "Total Value", "Condition", "Status"]} rows={rows.map((r) => [r.assetCode, r.name, r.category, r.quantity, r.available, `PKR ${r.unitCost}`, `PKR ${r.totalValue}`, r.condition, r.status])} />;
  } else if (key === "stock_in") {
    const rows = buildStockInReport(data);
    body = <Table headers={["Item", "Quantity", "Date", "Reason"]} rows={rows.map((r) => [r.item, r.quantity, r.date, r.reason])} />;
  } else if (key === "stock_out") {
    const rows = buildStockOutReport(data);
    body = <Table headers={["Item", "Quantity", "Date", "Reason"]} rows={rows.map((r) => [r.item, r.quantity, r.date, r.reason])} />;
  } else if (key === "assignment") {
    const rows = buildAssetAssignmentReport(data);
    body = <Table headers={["Item", "Qty", "Type", "Assigned To", "Date", "Reason"]} rows={rows.map((r) => [r.item, r.quantity, r.assignedToType, r.assignedTo, r.date, r.reason])} />;
  } else if (key === "low_stock") {
    const rows = buildLowStockReport(data);
    body = <Table headers={["Asset Code", "Item", "Available", "Minimum", "Shortfall"]} rows={rows.map((r) => [r.assetCode, r.name, r.available, r.minimumStock, r.shortfall])} />;
  } else if (key === "damaged") {
    const rows = buildDamagedItemsReport(data);
    body = <Table headers={["Asset Code", "Item", "Category", "Location", "Qty"]} rows={rows.map((r) => [r.assetCode, r.name, r.category, r.location, r.quantity])} />;
  } else if (key === "under_repair") {
    const rows = buildUnderRepairReport(data);
    body = <Table headers={["Asset Code", "Item", "Category", "Location", "Qty"]} rows={rows.map((r) => [r.assetCode, r.name, r.category, r.location, r.quantity])} />;
  } else if (key === "disposed") {
    const rows = buildDisposedItemsReport(data);
    body = <Table headers={["Asset Code", "Item", "Category", "Disposed Qty"]} rows={rows.map((r) => [r.assetCode, r.name, r.category, r.disposedQuantity])} />;
  } else {
    const rows = buildAssetValueReport(data);
    body = <Table headers={["Category", "Value"]} rows={rows.map((r) => [r.category, `PKR ${r.value}`])} />;
  }

  return (
    <div className="mx-auto max-w-4xl p-6 print:p-0">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <p className="text-sm text-muted">Print preview</p>
        <PrintButton />
      </div>
      <header className="mb-6 border-b-2 border-border pb-4 text-center">
        <h1 className="text-lg font-bold uppercase tracking-wide">{session.school.name}</h1>
        <p className="mt-2 text-base font-semibold">{TITLES[key] ?? "Inventory Report"}</p>
      </header>
      {body}
      <p className="mt-10 text-center text-xs text-muted">
        Generated by {session.profile.full_name} on {new Date().toLocaleString()} — {session.school.name}
      </p>
    </div>
  );
}
